# Generated by Django 5.2 on 2025-04-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TAN', 'Танки'), ('HEL', 'Хилы'), ('D_D', 'ДД'), ('MER', 'Торговцы'), ('GUM', 'Гилдмастеры'), ('GUG', 'Квестгиверы'), ('BLS', 'Кузнецы'), ('TNS', 'Кожевники'), ('POT', 'Зельевары'), ('SPL', 'Мастера заклинаний')], max_length=3, verbose_name='Категория')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('heading', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('text', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('CN', 'Рассмотрение'), ('AD', 'Принят'), ('RE', 'Отклонён')], max_length=2, verbose_name='Статус')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.posts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
